# These are supported funding model platforms

github: gitclone93, webdevcode93
patreon: Infection Game
open_collective: 
ko_fi: 
tidelift: 
community_bridge:
liberapay:
issuehunt:
otechie: 
custom: 
